-- Test-only schema snapshot from the inspected production definitions. No customer data.
create role anon; create role authenticated; create role service_role;
create schema auth; create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;
create table public.crm_account_access (
  user_id uuid not null,
  email text,
  status text default 'pending'::text not null,
  is_admin boolean default false not null,
  created_at timestamp with time zone default now() not null,
  reviewed_at timestamp with time zone,
  reviewed_by uuid
);
create table public.customers (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  name text not null,
  phone text,
  email text,
  city text,
  source text,
  status text default 'Customer'::text not null,
  priority text default 'Normal'::text not null,
  notes text,
  archived boolean default false not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  language text default 'English'::text not null
);
create table public.leads (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  customer_id uuid not null,
  lead_number bigint generated by default as identity not null,
  vehicle text,
  stock_number text,
  source text,
  status text default 'New'::text not null,
  priority text default 'Normal'::text not null,
  next_action_at timestamp with time zone,
  notes text,
  archived boolean default false not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  sale_price numeric,
  gross_profit numeric,
  sold_at timestamp with time zone,
  lost_reason text
);
create table public.lead_history (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  lead_id uuid not null,
  event_type text not null,
  note text,
  occurred_at timestamp with time zone default now() not null
);
create table public.followups (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  customer_id uuid not null,
  lead_id uuid,
  action_type text not null,
  scheduled_at timestamp with time zone not null,
  status text default 'Open'::text not null,
  notes text,
  created_at timestamp with time zone default now() not null,
  delivery_id uuid,
  finance_contract_id uuid,
  lease_contract_id uuid
);
create table public.leases (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  customer_id uuid not null,
  transaction_number text,
  stock_number text,
  vehicle text not null,
  vin text,
  delivery_date date,
  term_months integer,
  lease_end_date date,
  payment_mode text,
  sales_rep text,
  notes text,
  created_at timestamp with time zone default now() not null,
  opportunity_status text default 'Not contacted'::text not null,
  last_contact_at timestamp with time zone,
  next_contact_at timestamp with time zone,
  last_contact_notes text,
  closed_at timestamp with time zone,
  removed_at timestamp with time zone,
  removal_reason text
);
create table public.finance_contracts (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  customer_id uuid not null,
  vehicle text not null,
  delivery_date date,
  term_months integer,
  last_payment_date date,
  payment_mode text default 'Financing'::text not null,
  import_key text,
  notes text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  opportunity_status text default 'Not contacted'::text not null,
  last_contact_at timestamp with time zone,
  next_contact_at timestamp with time zone,
  last_contact_notes text,
  closed_at timestamp with time zone
);
create table public.lease_outreach_history (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  lease_contract_id uuid not null,
  customer_id uuid not null,
  outcome text not null,
  notes text,
  next_contact_at timestamp with time zone,
  followup_id uuid,
  created_at timestamp with time zone default now() not null
);
create table public.finance_outreach_history (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  finance_contract_id uuid not null,
  customer_id uuid not null,
  outcome text not null,
  notes text,
  next_contact_at timestamp with time zone,
  followup_id uuid,
  created_at timestamp with time zone default now() not null
);
create table public.deliveries (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  customer_id uuid not null,
  lead_id uuid,
  vehicle text not null,
  stock_number text,
  prep_date date,
  delivery_at timestamp with time zone,
  status text default 'In Prep'::text not null,
  notes text,
  created_at timestamp with time zone default now() not null
);
create table public.orders (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  customer_id uuid not null,
  lead_id uuid,
  vehicle text not null,
  trim text,
  color text,
  order_date date default CURRENT_DATE not null,
  expected_wait text,
  estimated_arrival date,
  status text default 'Ordered'::text not null,
  notes text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);
create table public.daily_priority_calls (
  id uuid default gen_random_uuid() not null,
  owner_id uuid default auth.uid() not null,
  call_date date default ((now() AT TIME ZONE 'America/Toronto'::text))::date not null,
  customer_id uuid not null,
  opportunity_type text not null,
  opportunity_id uuid not null,
  vehicle text,
  priority_score integer default 0 not null,
  priority_level text not null,
  priority_reason text not null,
  result text not null,
  notes text,
  next_action_at timestamp with time zone,
  completed_at timestamp with time zone default now() not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);
alter table public.lead_history add constraint "lead_history_pkey" PRIMARY KEY (id);
alter table public.customers add constraint "customers_pkey" PRIMARY KEY (id);
alter table public.leads add constraint "leads_pkey" PRIMARY KEY (id);
alter table public.finance_contracts add constraint "finance_contracts_owner_import_key_unique" UNIQUE (owner_id, import_key);
alter table public.followups add constraint "followups_pkey" PRIMARY KEY (id);
alter table public.deliveries add constraint "deliveries_status_check" CHECK ((status = ANY (ARRAY['In Prep'::text, 'Ready'::text, 'Delivered'::text])));
alter table public.deliveries add constraint "deliveries_pkey" PRIMARY KEY (id);
alter table public.leases add constraint "leases_pkey" PRIMARY KEY (id);
alter table public.orders add constraint "orders_pkey" PRIMARY KEY (id);
alter table public.crm_account_access add constraint "crm_account_access_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])));
alter table public.crm_account_access add constraint "crm_account_access_pkey" PRIMARY KEY (user_id);
alter table public.customers add constraint "customers_language_check" CHECK ((language = ANY (ARRAY['English'::text, 'French'::text])));
alter table public.finance_contracts add constraint "finance_contracts_term_months_check" CHECK (((term_months IS NULL) OR ((term_months >= 1) AND (term_months <= 120))));
alter table public.finance_contracts add constraint "finance_contracts_pkey" PRIMARY KEY (id);
alter table public.finance_outreach_history add constraint "finance_outreach_history_pkey" PRIMARY KEY (id);
alter table public.daily_priority_calls add constraint "daily_priority_calls_priority_score_check" CHECK (((priority_score >= '-500'::integer) AND (priority_score <= 1000)));
alter table public.lease_outreach_history add constraint "lease_outreach_history_pkey" PRIMARY KEY (id);
alter table public.finance_contracts add constraint "finance_contracts_opportunity_status_check" CHECK ((opportunity_status = ANY (ARRAY['Not contacted'::text, 'Interested'::text, 'Follow-up scheduled'::text, 'Keeping vehicle'::text, 'No answer'::text, 'Left voicemail'::text, 'Spoke'::text, 'Sold'::text, 'Lost'::text, 'Do Not Contact'::text])));
alter table public.finance_outreach_history add constraint "finance_outreach_history_outcome_check" CHECK ((outcome = ANY (ARRAY['Interested'::text, 'Follow up later'::text, 'Keeping vehicle'::text, 'No answer'::text, 'Left voicemail'::text, 'Spoke'::text, 'Appointment booked'::text, 'Changing vehicle'::text, 'Sold'::text, 'Lost'::text, 'Do Not Contact'::text])));
alter table public.leases add constraint "leases_opportunity_status_check" CHECK ((opportunity_status = ANY (ARRAY['Not contacted'::text, 'Interested'::text, 'Follow-up scheduled'::text, 'Buying out lease'::text, 'Returning vehicle'::text, 'No answer'::text, 'Left voicemail'::text, 'Spoke'::text, 'Not interested'::text, 'Sold'::text, 'Lost'::text, 'Do Not Contact'::text])));
alter table public.lease_outreach_history add constraint "lease_outreach_history_outcome_check" CHECK ((outcome = ANY (ARRAY['Interested in upgrading'::text, 'Follow up later'::text, 'Buying out lease'::text, 'Returning vehicle'::text, 'No answer'::text, 'Not interested'::text, 'Left voicemail'::text, 'Spoke'::text, 'Interested'::text, 'Appointment booked'::text, 'Keeping vehicle'::text, 'Changing vehicle'::text, 'Sold'::text, 'Lost'::text, 'Do Not Contact'::text])));
alter table public.daily_priority_calls add constraint "daily_priority_calls_opportunity_type_check" CHECK ((opportunity_type = ANY (ARRAY['Lead'::text, 'Lease'::text, 'Finance'::text])));
alter table public.daily_priority_calls add constraint "daily_priority_calls_priority_level_check" CHECK ((priority_level = ANY (ARRAY['Urgent'::text, 'High'::text, 'Medium'::text])));
alter table public.daily_priority_calls add constraint "daily_priority_calls_result_check" CHECK ((result = ANY (ARRAY['No answer'::text, 'Left voicemail'::text, 'Spoke'::text, 'Interested'::text, 'Appointment booked'::text, 'Follow up later'::text, 'Keeping vehicle'::text, 'Changing vehicle'::text, 'Sold'::text, 'Lost'::text, 'Do Not Contact'::text])));
alter table public.daily_priority_calls add constraint "daily_priority_calls_pkey" PRIMARY KEY (id);
alter table public.daily_priority_calls add constraint "daily_priority_calls_owner_id_call_date_opportunity_type_op_key" UNIQUE (owner_id, call_date, opportunity_type, opportunity_id);
alter table public.leads add constraint "leads_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.lead_history add constraint "lead_history_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.customers add constraint "customers_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.leads add constraint "leads_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.lead_history add constraint "lead_history_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.followups add constraint "followups_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.followups add constraint "followups_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.followups add constraint "followups_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
alter table public.deliveries add constraint "deliveries_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.deliveries add constraint "deliveries_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.deliveries add constraint "deliveries_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.leases add constraint "leases_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.leases add constraint "leases_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.orders add constraint "orders_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.orders add constraint "orders_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.orders add constraint "orders_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;
alter table public.crm_account_access add constraint "crm_account_access_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.crm_account_access add constraint "crm_account_access_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
alter table public.followups add constraint "followups_delivery_id_fkey" FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE;
alter table public.finance_contracts add constraint "finance_contracts_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id);
alter table public.finance_contracts add constraint "finance_contracts_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id);
alter table public.followups add constraint "followups_finance_contract_id_fkey" FOREIGN KEY (finance_contract_id) REFERENCES finance_contracts(id) ON DELETE SET NULL;
alter table public.finance_outreach_history add constraint "finance_outreach_history_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.finance_outreach_history add constraint "finance_outreach_history_finance_contract_id_fkey" FOREIGN KEY (finance_contract_id) REFERENCES finance_contracts(id) ON DELETE CASCADE;
alter table public.finance_outreach_history add constraint "finance_outreach_history_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.finance_outreach_history add constraint "finance_outreach_history_followup_id_fkey" FOREIGN KEY (followup_id) REFERENCES followups(id) ON DELETE SET NULL;
alter table public.followups add constraint "followups_lease_contract_id_fkey" FOREIGN KEY (lease_contract_id) REFERENCES leases(id) ON DELETE SET NULL;
alter table public.lease_outreach_history add constraint "lease_outreach_history_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.lease_outreach_history add constraint "lease_outreach_history_lease_contract_id_fkey" FOREIGN KEY (lease_contract_id) REFERENCES leases(id) ON DELETE CASCADE;
alter table public.lease_outreach_history add constraint "lease_outreach_history_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.lease_outreach_history add constraint "lease_outreach_history_followup_id_fkey" FOREIGN KEY (followup_id) REFERENCES followups(id) ON DELETE SET NULL;
alter table public.daily_priority_calls add constraint "daily_priority_calls_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.daily_priority_calls add constraint "daily_priority_calls_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
CREATE OR REPLACE FUNCTION public.crm_is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.crm_account_access a
    where a.user_id = auth.uid() and a.is_admin = true and a.status = 'approved'
  );
$function$
;
CREATE OR REPLACE FUNCTION public.crm_is_approved()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.crm_account_access a
    where a.user_id = auth.uid() and a.status = 'approved'
  );
$function$
;
CREATE OR REPLACE FUNCTION public.schedule_post_delivery_thank_you()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if new.status = 'Delivered' then
    insert into public.followups (owner_id, customer_id, lead_id, delivery_id, action_type, scheduled_at, status, notes)
    values (
      new.owner_id,
      new.customer_id,
      new.lead_id,
      new.id,
      'Post-delivery thank you',
      coalesce(new.delivery_at, now()) + interval '1 day',
      'Open',
      'Send a thank-you / check-in text after delivery.'
    )
    on conflict (delivery_id) where delivery_id is not null and action_type = 'Post-delivery thank you'
    do update set
      customer_id = excluded.customer_id,
      lead_id = excluded.lead_id,
      scheduled_at = excluded.scheduled_at;
  elsif tg_op = 'UPDATE' and old.status = 'Delivered' and new.status <> 'Delivered' then
    delete from public.followups
    where delivery_id = new.id
      and action_type = 'Post-delivery thank you'
      and status = 'Open';
  end if;
  return new;
end;
$function$
;
alter table public.crm_account_access enable row level security;
grant select,insert,update,delete on public.crm_account_access to authenticated;
alter table public.customers enable row level security;
grant select,insert,update,delete on public.customers to authenticated;
alter table public.leads enable row level security;
grant select,insert,update,delete on public.leads to authenticated;
alter table public.lead_history enable row level security;
grant select,insert,update,delete on public.lead_history to authenticated;
alter table public.followups enable row level security;
grant select,insert,update,delete on public.followups to authenticated;
alter table public.leases enable row level security;
grant select,insert,update,delete on public.leases to authenticated;
alter table public.finance_contracts enable row level security;
grant select,insert,update,delete on public.finance_contracts to authenticated;
alter table public.lease_outreach_history enable row level security;
grant select,insert,update,delete on public.lease_outreach_history to authenticated;
alter table public.finance_outreach_history enable row level security;
grant select,insert,update,delete on public.finance_outreach_history to authenticated;
alter table public.deliveries enable row level security;
grant select,insert,update,delete on public.deliveries to authenticated;
alter table public.orders enable row level security;
grant select,insert,update,delete on public.orders to authenticated;
alter table public.daily_priority_calls enable row level security;
grant select,insert,update,delete on public.daily_priority_calls to authenticated;
grant usage,select on all sequences in schema public to authenticated;
create policy "customers_owner_all" on public.customers as PERMISSIVE for ALL to authenticated using (((owner_id = auth.uid()) AND crm_is_approved())) with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "crm_access_read_own_or_admin" on public.crm_account_access as PERMISSIVE for SELECT to authenticated using (((user_id = auth.uid()) OR crm_is_admin()));
create policy "leases_owner_all" on public.leases as PERMISSIVE for ALL to authenticated using (((owner_id = auth.uid()) AND crm_is_approved())) with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "leads_owner_all" on public.leads as PERMISSIVE for ALL to authenticated using (((owner_id = auth.uid()) AND crm_is_approved())) with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "followups_owner_all" on public.followups as PERMISSIVE for ALL to authenticated using (((owner_id = auth.uid()) AND crm_is_approved())) with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "deliveries_owner_all" on public.deliveries as PERMISSIVE for ALL to authenticated using (((owner_id = auth.uid()) AND crm_is_approved())) with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "history_owner_all" on public.lead_history as PERMISSIVE for ALL to authenticated using (((owner_id = auth.uid()) AND crm_is_approved())) with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "orders_select_own" on public.orders as PERMISSIVE for SELECT to authenticated using (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "orders_insert_own" on public.orders as PERMISSIVE for INSERT to authenticated with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "orders_update_own" on public.orders as PERMISSIVE for UPDATE to authenticated using (((owner_id = auth.uid()) AND crm_is_approved())) with check (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "orders_delete_own" on public.orders as PERMISSIVE for DELETE to authenticated using (((owner_id = auth.uid()) AND crm_is_approved()));
create policy "finance_contracts_owner_all" on public.finance_contracts as PERMISSIVE for ALL to authenticated using (((owner_id = ( SELECT auth.uid() AS uid)) AND crm_is_approved())) with check (((owner_id = ( SELECT auth.uid() AS uid)) AND crm_is_approved()));
create policy "finance_outreach_owner_all" on public.finance_outreach_history as PERMISSIVE for ALL to authenticated using (((owner_id = ( SELECT auth.uid() AS uid)) AND crm_is_approved())) with check (((owner_id = ( SELECT auth.uid() AS uid)) AND crm_is_approved()));
create policy "lease_outreach_owner_all" on public.lease_outreach_history as PERMISSIVE for ALL to authenticated using (((owner_id = ( SELECT auth.uid() AS uid)) AND crm_is_approved())) with check (((owner_id = ( SELECT auth.uid() AS uid)) AND crm_is_approved()));
create policy "daily_priority_calls_owner_all" on public.daily_priority_calls as PERMISSIVE for ALL to authenticated using (((( SELECT auth.uid() AS uid) = owner_id) AND crm_is_approved())) with check (((( SELECT auth.uid() AS uid) = owner_id) AND crm_is_approved()));
create unique index followup_delivery_thankyou on public.followups(delivery_id) where delivery_id is not null and action_type='Post-delivery thank you';
create trigger deliveries_thankyou after insert or update of status,delivery_at,customer_id,lead_id on public.deliveries for each row execute function public.schedule_post_delivery_thank_you();
